### ISSUE TITLE
Update tendrl-ansible for Tendrl Milestone #3 (2nd milestone)

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/tendrl-ansible#23]
Tendrl ansible needs to be updated for https://github.com/Tendrl/specifications/milestone/3

Related specifications (I went through all items listed in the milestone and searched for configuration, setup and documentation impact, here I'm tracking changes in tendrl-ansible based on that, and questions when the impact is not clear):

* [x] https://github.com/Tendrl/specifications/issues/233 `tendrl-monitoring-integration` was turned into a daemon:
  * [x] question https://github.com/Tendrl/specifications/issues/233#issuecomment-324088908
  * [x] validate commit  https://github.com/Tendrl/tendrl-ansible/pull/24/commits/8585704e92c10538ae7f3f13f9242f6bd8ebafe3 (1st try to address the change)
  * [x] issue with config or bug: tendrl dashboards not loaded in grafana, see: https://paste.fedoraproject.org/paste/oXpvMpmhGTIHmsmctIQ0cQ
* [x] https://github.com/Tendrl/specifications/issues/179 new monitoring-integration component
  * I assume that there are no new impact for this milestone wrt tendrl-ansible, but I couldn't to verify this assumption so far
  * [x] question https://github.com/Tendrl/specifications/issues/179#issuecomment-324097632 (issue/specification is shared with multiple milestones, so I'm unable to tell what is done for this one and what configuration/setup impact will be) - I assume there is nothing I should be aware of with respect of this milestone here https://github.com/Tendrl/specifications/issues/179#issuecomment-324400666

See also Install Guide:

* https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference
* https://github.com/Tendrl/specifications/issues/245

Known Problems (making tendrl-ansible based installation fail):

* [x] https://github.com/Tendrl/monitoring-integration/issues/33

**Comment by mbukatov** [comment]
@mkudlej I finished the review of all specification issues of milestone 3 and evaluated impact on tendrl-ansible changes.

**Comment by mbukatov** [comment]
Resolved by https://github.com/Tendrl/tendrl-ansible/pull/24 with one known issue:

https://github.com/Tendrl/monitoring-integration/issues/33
