### ISSUE TITLE
Update tendrl-ansible for Tendrl Milestone #1 (3rd milestone)

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/tendrl-ansible#25]
Tendrl ansible needs to be updated for [Gluster Monitoring milestone](https://github.com/Tendrl/specifications/milestone/1)

Related specifications (only specifications originally listed in previous milestone #2 are mentioned there, full review is needed):

* [ ]  additional review of items linked to the milestone is needed (the last time I did full review this was about 3 weeks ago)

* https://github.com/Tendrl/specifications/issues/172
  * it has been removed from the milestone, now it's not linked to any milestone, which means that this is out completely
  * this seems to have a significant impact on configuration and setup of tendrl (confirmed by dev team)
  * specification: https://github.com/Tendrl/specifications/pull/174
  * question https://github.com/Tendrl/specifications/issues/172#issuecomment-324092859
  * [x] question https://github.com/Tendrl/specifications/pull/174/files#r134545678
  * question https://github.com/Tendrl/specifications/pull/174/files#r131070822
  * question https://github.com/Tendrl/specifications/pull/174/files#r134547834
* [x] https://github.com/Tendrl/specifications/issues/190 alerting renamed to notifier
  * note that in 1st milestone, alerting component was completely removed, see 02da221ec330d11f002202d8bb4ad525900cf778
  * [x] question https://github.com/Tendrl/specifications/issues/190#issuecomment-324100169 (details provided in https://github.com/Tendrl/tendrl-ansible/issues/33)
* [x] https://github.com/Tendrl/specifications/issues/169 review for changes in setup
  * question https://github.com/Tendrl/specifications/pull/198#discussion_r134161044 (based on the description, I'm unable to understand the impact, on one hand it seems that there is none, but on the other, I'm little confused about this change so I may be wrong)
  * there is no feedback, so I'm going to assume that there is no impact on tendrl-ansible
* [x] https://github.com/Tendrl/specifications/issues/191 Authentication and Authorisation linkage between tendrl ui and grafana
  * see https://github.com/Tendrl/specifications/issues/191#issuecomment-326197800
  * described in https://github.com/Tendrl/tendrl-ansible/issues/32

**Comment by mbukatov** [comment]
I'm closing this without full milestone review, assuming that all changes required were reported to tendrl-ansible with all details and links.
